on:
  push:
    branches:
      - master

jobs:
  gprActionJob:
    name: GPR Action Job
  steps:
    - name: Checkout
      uses: actions/checkout@v1.0.0
    - name: Gpr action step
      uses: whitesource-yossi/gpraction@master