on: 
  push:
    branches:    
      - jsHello 

jobs:
  example:
    name: JS hello world
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1.0.0
    - name: Hello world action step
      env:
        FIRST_NAME: Mona Lisa
        myToken: ${{ secrets.GITHUB_TOKEN }}
      uses: ./.github/actions/js-hello-world
      with:
        who-to-greet: 'Yos'